# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
    ]
