# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170203_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_photo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_photo', to='portfolio.Photo'),
            preserve_default=False,
        ),
    ]
