# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_photo',
        ),
    ]
