# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170204_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='main_photo',
        ),
    ]
