# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_photo_main_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='main_photo_credit',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='', upload_to='project_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.Project'),
        ),
    ]
