# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170205_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.IntegerField(choices=[(500, 'Vertical'), (1200, 'Horizontal')], default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='orientation',
            field=models.IntegerField(choices=[(500, 'Vertical'), (1200, 'Horizontal')], default=1200),
            preserve_default=False,
        ),
    ]
