# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20170205_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='orientation',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='orientation',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], max_length=1),
        ),
    ]
