# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20170207_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
