# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20170207_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='press/')),
                ('pdf', models.FileField(blank=True, upload_to='press/')),
                ('link', models.URLField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
        ),
    ]
