# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
