# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20170208_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press', to='portfolio.Project'),
        ),
    ]
