# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20170208_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name_plural': 'Press'},
        ),
        migrations.AddField(
            model_name='press',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
