# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_photo_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='publication_type',
            field=models.CharField(choices=[('B', 'Book'), ('M', 'Magazine')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
