# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_press_publication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='project_photos/')),
                ('orientation', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], max_length=1)),
                ('display_order', models.IntegerField()),
                ('credit', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('full_width_photo', models.BooleanField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
