# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='text',
        ),
    ]
